version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging in to AMAZON ECR ...
       #- $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
       - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 428645345788.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
       - echo Build started on 'date'
       - echo Building the Docker image...
       - docker build -t repo .
       - docker tag repo:latest 428645345788.dkr.ecr.ap-south-1.amazonaws.com/repo:latest
  post_build:
    commands:
       - echo Build completed on 'date'
       - echo pushing the docker image...
       - docker push 428645345788.dkr.ecr.ap-south-1.amazonaws.com/repo:latest
