version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging in to AMAZON ECR ...
       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      # - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m9y3o0k4
  build:
    commands:
       - echo Build started on 'date'
       - echo Building the Docker image...
       - docker build -t web:1 .
       - docker tag web:1 public.ecr.aws/m9y3o0k4/repo
  post_build:
    commands:
       - echo Build completed on 'date'
       - echo pushing the docker image...
       - docker push public.ecr.aws/m9y3o0k4/repo